### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by giuseppetacconelli** [vuejs/docs-next#1073]
Hi,
Do you have a release schedule for new versions? Do you have a long-term support version?

Thank you

**Comment by skirtles-code** [comment]
I don't believe there is a schedule of this kind.

2.7 is due to be supported for 18 months after it's released. That will include back-ports of several Vue 3 features. 2.6 is still being actively maintained for essential updates in the meantime.

3.1.1 is currently the latest release for Vue 3. There isn't an LTS version as such. If you're using Vue 3 then you should aim to be on the latest version.

If you have any further questions, I suggest asking on [Vue Land Discord](https://chat.vuejs.org/).
