### ISSUE TITLE
Unusable state after a fresh deployment

### ISSUE THREAD

**Issue by CyberAP** [vuejs/docs-next#258]
After a new deployment users who were on the site prior to the deployment will get this error:

> Uncaught (in promise) ChunkLoadError: Loading chunk 79 failed.

The site will become unusable until the page is refreshed.

I am not quite sure where exactly to put the fix:

```js
errorCaptured(error) {
  if (error.name === 'ChunkLoadError') {
    document.location.reload(true);
  }
}
```

**Comment by NataliaTepluhina** [comment]
Hmmm, should we file an issue on VuePress repository? I don't think it's a docs-specific thing 🤔

**Comment by CyberAP** [comment]
It is a deployment-dependent thing. Current deployment destroys links to previous chunks making them unreachable.

**Comment by NataliaTepluhina** [comment]
@CyberAP I would still insist it's a VuePress+Netlify related error: https://github.com/vuejs/vuepress/issues/2090 and should be rather fixed on VuePress to prevent the same kind of errors on all VuePress projects (as far as I remember Gatsby did an effort to add an error handler to their source code).

I will try to think where we could put a handler like this but it still feels like a hack to me to fix a project created with the platform rather than platform itself.

**Comment by NataliaTepluhina** [comment]
Closing as a stale one
