### ISSUE TITLE
vue3.0 为什么在脚手架里面使用 createApp(AttributeBinding).mount('#bind-attribute') 的例子会把 #bind-attribute 里面的内容清空，并且没有渲染出其他内容

### ISSUE THREAD

**Issue by tfeng-use** [vuejs/docs-next#546]
连接：https://v3.vuejs.org/guide/introduction.html#declarative-rendering

**Comment by fnick851** [comment]
@tfeng-use 
一个建议：如果不是中文文档独有的问题，建议用英文提问。Vue core team能读懂中文的估计没几个。尤其你给的链接还是英文文档的。而且你的问题听起来更应该去Vue CLI仓库底下问。
An unofficial recommendation: If the issue is not specific to the Chinese version of documentation, I think it is better to write the issue in English, especially when you are linking to the English doc. I don't think there are many in the Vue core team who can read Chinese. Also, it sounds like your issue belongs to the Vue CLI repo.
