### ISSUE TITLE
V-modal.trim

### ISSUE THREAD

**Issue by andrewpremo** [vuejs/docs-next#559]
V-modal.trim does not work.

**Comment by skirtles-code** [comment]
`v-model.trim` seems to be working for me:

https://jsfiddle.net/skirtle/nr7jhyfb/

This issues list is for reporting problems with the documentation. If you think the documentation needs changing could you elaborate on exactly what the problem is?

If you think there's a bug in Vue 3 could you please report it against the `vue-next` repo instead?

If you want help debugging your code, or you have a usage question, I suggest asking on the forums, the discord channel or Stack Overflow.
