### ISSUE TITLE
Vue-Route improper redirect

### ISSUE THREAD

**Issue by nford-bt** [vuejs/docs-next#653]
We are using devexpress/TestCafe to run automated tests against Vue. The automation works by appending a host IP, port, and GUID to the prefix of the URL. See bold in the example: http://**localhost:58464/hFaxIQgx6**/https://thisisatestURL.net

On Vue 2, when we ran our test automation, we had no issues navigating to the correct URLs. 
(ex. http://**localhost:58464/hFaxIQgx6**/https://thisisatestURL.net)

On Vue 3, when we run the automation, the following URL is displayed: http://localhost:58464/hFaxIQgx6/https://thisisatestURL.net/hFaxIQgx6/https://thisisatestURL.net

This is an invalid URL. It looks like the root of the URL is duplicated along with the GUID. As a result, our catch all redirects to a different webpage which is causing significant failures.

Considering the automation worked with Vue 2, it looks like there is an issue with Vue 3.

**Comment by NataliaTepluhina** [comment]
I don't think this issue is relevant for the docs repository though 🤔 Without knowing your automated tests configuration and the project structure it's impossible to say the root cause of the issue - be it Vue 3 or Vue Router or something else. I would recommend building a minimal reproduction to find out what's causing the incorrect behavior and then opening an issue on the respective repository.
