### ISSUE TITLE
组件指令究竟能不能被 $attrs 移植在非根目标上？

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/docs-next#655]
> ### Implementation Details
> In Vue 3, we're now supporting fragments, which allow us to return more than one DOM node per component. You can imagine how handy that is for something like a component with multiple \<li> elements or the children elements of a table:
> As wonderfully flexible as this is, we can potentially encounter a problem with a custom directive that could have multiple root nodes.
> As a result, custom directives are now included as part of a virtual DOM node’s data. When a custom directive is used on a component, hooks are passed down to the component as extraneous props and end up in this.$attrs.
> This also means it's possible to directly hook into an element's lifecycle like this in the template, which can be handy when a custom directive is too involved:
> This is consistent with the attribute fallthrough behavior, so when a child component uses v-bind="$attrs" on an inner element, it will apply any custom directives used on it as well.

根据这里的意思，是能。

> ### Usage on Components
> When used on components, custom directive will always apply to component's root node, similarly to non-prop attributes.
> Unlike attributes, directives can't be passed to a different element with v-bind="$attrs".
> With fragments support, components can potentially have more than one root nodes. When applied to a multi-root component, directive will be ignored and the warning will be thrown.

根据这里的意思，似乎不能。而且测试了一下，似乎确实不能通过 v-bind="$attrs" 自主指定组件上指令的挂载点，无论是否是 fragments，因为指令钩子并未出现在 console.log($attrs) 中。

但这感觉是个好功能。是还没来得及实现吗？

**Comment by skirtles-code** [comment]
The first quote is from the migration guide. It is incorrect and needs to be updated:

https://github.com/vuejs/docs-next/blame/9b463de65184751a69b45e931bc4508a82d04978/src/guide/migration/custom-directives.md#L106

The second quote is from the recently updated documentation for custom directives. See #646. It accurately describes the current behaviour.

@LongTengDao I believe you're asking whether this feature could be implemented as described in that first quote. I don't believe it can, as directives such as `v-show` assume they're being applied to the root element. Having directives follow the `$attrs` would not be the expected behaviour in such cases.
