### ISSUE TITLE
Add setup steps + boilerplate repos for library authors

### ISSUE THREAD

**Issue by JessicaSachs** [vuejs/docs-next#660]
I was looking through the docs for guidance on building libraries (specifically bundling w/ rollup) and didn't see a Getting Started section.

I ended up finding Posva's boilerplate and was wondering if we should add some of these to the docs? https://github.com/posva/vue-ts-lib

**Comment by JessicaSachs** [comment]
Perhaps right here https://github.com/vuejs/docs-next/blob/4510533fd58bb178f60857690b594ea6d49d6ffb/src/guide/single-file-component.md#L63-L67

**Comment by znck** [comment]
We have some examples on the RPV repo (https://github.com/vuejs/rollup-plugin-vue/tree/next/examples), but we definitely need better documentation.

**Comment by NataliaTepluhina** [comment]
I like the idea but I don't have enough experience with building plugins. I'll mark this as open for community contributions.

**Comment by DonNicoJs** [comment]
@NataliaTepluhina Thanks for showing me this! As I've just recently went through this exact process for: https://github.com/vue-leaflet/vue-leaflet

I can summarise my experience on an addition for the docs (since is rather fresh!) I would touch this points:

- General intro
- How to use the composition API
- How to bundle with rollup
- How to create esm / UMD  and CJS bundles
- Quirks and gotchas 

Note that rollup-plugin-vue has still few bugs, but they are workaround-able

If this sounds good I am happy to work on this!

**Comment by NataliaTepluhina** [comment]
@DonNicoJs thank you for willing to help! If you don't mind, I'll assign this issue to you then 👍🏻 

Please feel free to ping me if you have any questions and I will be happy to review the PR!

**Comment by znck** [comment]
@DonNicoJs feel free to reach me, regarding RPV or anything else needed for this.
