### ISSUE TITLE
Missing prototype replacement section in migration guide

### ISSUE THREAD

**Issue by cathrinevaage** [vuejs/docs-next#700]
When migrating a vue 2 app, one would likely refer to the migration guide.
Information about how `Vue.prototype.$foo` has been replaced by `app.config.globalProperties.$foo` can not be found.
This is a question that appears pretty frequently in the VueLand vue 3 code help channel, and I think it's deserving of its own section in the migration guide.

**Comment by skirtles-code** [comment]
At the RFC stage it was documented here:

https://github.com/vuejs/rfcs/blob/master/active-rfcs/0009-global-api-change.md

It seems that it didn't make it through to the equivalent page in the migration guide, perhaps because it was a late addition to the RFC.

It definitely needs to be in the migration guide somewhere.
