### ISSUE TITLE
Use ref in v-for get wrong element in Vue@3.0.0-rc.13 & 3.0.1 & 3.0.2

### ISSUE THREAD

**Issue by Derek-DZ** [vuejs/docs-next#703]
### Version
3.0.0-rc.13

### Reproduction link
https://codepen.io/derek-dz/pen/VwjOJLa?editors=0010

### Steps to reproduce 

1. click the button tab1/tab2
2. see the Console is tab2/tab1

### What is expented?

- click the button tab1 and console tab1
- click the button tab2 and console tab2
  (in version 3.0.0-rc.6 ~ 12 is ok)

### What is actually happening?

- click the button tab1 and console tab2
- click the button tab2 and console tab1
  (in version 3.0.0-rc.13 only)

**Comment by NataliaTepluhina** [comment]
@Derek-DZ is this reproducing on the current version (3.0.2 as of today)?

**Comment by Derek-DZ** [comment]
@NataliaTepluhina in version 3.0.2 get the wrong result too.

**Comment by NataliaTepluhina** [comment]
@Derek-DZ I believe this is not a bug but an expected behavior: since Vue 3.0.0-rc.13 [watch APIs default to use `flush: 'pre'` instead of `flush: 'post'`](https://github.com/vuejs/vue-next/commit/49bb44756fda0a7019c69f2fa6b880d9e41125aa)

To achieve a desired (pre-rc.13) behavior, you can modify `watchEffect` in your example with `flush: post`:

```
        watchEffect(() => {
          if (selectedItem) {
            console.log(selectedItem.value.textContent);
          }
           
        },  { flush: 'post' });
```
