### ISSUE TITLE
组件使用defineAsyncComponent引入局部注册，触发计算属性$refs下挂载的组件被清空。

### ISSUE THREAD

**Issue by guagezuishuai** [vuejs/docs-next#757]
<addprogram @selectRes="selectRes" ref="addprogramRef"></addprogram>

const { ctx } = getCurrentInstance();
const addAdvertisementRef = ref(null);
computed(() => Math.round(totalSize.value * 100) / 100)
addAdvertisementRef.value.dialogVisible = true;

第一次点击正常，但是我通过selectRes方法触发父组件的计算属性，我的addAdvertisementRef的value就成null了，ctx删挂载的子组件的实例也被清空了

**Comment by NataliaTepluhina** [comment]
Sorry, but I don't think this issue is related to the documentation.

Please post questions to the [Vue Discord chat](https://chat.vuejs.org/), the [Vue Forum](https://forum.vuejs.org/) or  [Stack Overflow](https://stackoverflow.com/). This issues list is for reporting problems with the documentation.
