### ISSUE TITLE
[Question] For v3's tutorial, is the introduction meant for v2?

### ISSUE THREAD

**Issue by Aldo111** [vuejs/docs-next#842]
Hi, I was looking to try out VueJS, wanting to take a break from using AngularDart on various heavy apps, but I was somewhat confused by the introduction. It seems the composition API is the preferred way of managing components going forward in v3 but the introduction relies on the old v2 syntax.

Is this intended for people who are looking to migrate from v2 or is the v2 syntax intended to be fully supported in v3 forever? (I thought it was the opposite from the migration guide).

Just trying to understand what the best flow of learning the v3 side of things is as I'm somewhat confused at the moment.

Thanks and looking forward to getting into vue!

**Comment by skirtles-code** [comment]
I suggest using [Vue Discord](https://chat.vuejs.org/) for questions, you'll usually get a pretty quick response on there.

The Vue 3 guide introduces the options API first, which is the API from Vue 2. This API is alive and well and is what a lot of projects are using. I'm not sure what you saw in the migration guide to make you think otherwise but learning the options API first is still a really good way to get into Vue.

The composition API gets a lot of publicity because it is new. The buzz is always going to be around the shiny new features rather than the features that have been around for ages. The options API is still very popular.

One of the primary goals of the composition API was to make it easier to build components by sticking pieces together. In Vue 2 that could be achieved by using `extends` and `mixins`. Those two options do still exists but for new code it would usually be better to use the composition API instead. This doesn't mean you have to do everything using the composition API. Some people use it everywhere, some just use it in more advanced scenarios as a replacement for mixins.

The Vue 3 guide should be an accurate reflection of the current state of Vue, though we're always looking for ways to improve it to better reflect how Vue is used in the real world.

**Comment by Aldo111** [comment]
Got it, thanks for that clarification! Excited to get into it and looking forward to the future of Vue!
