### ISSUE TITLE
Documentation:  watch over nested objects, the right way.

### ISSUE THREAD

**Issue by Mr-Ruben** [vuejs/docs-next#908]
As seen here, many people fall on this trap and the solution is very simple yet undocumented
https://stackoverflow.com/a/46331968/4752223

Doesn't work
```
watch:{
     item.someOtherProp: function (newVal, oldVal){

```
Does work
```
watch:{
     'item.someOtherProp': function (newVal, oldVal){


```
The difference (ticks surrounding the object to watch):
`item.someOtherProp -> 'item.someOtherProp'`

Look at the first comment to that answer

> way more elegant (not just a bit) :P. This should be in Vue.js documentation as it is a common use case. I've been searching for hours for a solution, thanks for your answer. –

![image](https://user-images.githubusercontent.com/37179353/108943943-02bce480-765a-11eb-9631-70bfd71d2fb2.png)

You may say that it is already in the documentation  -> https://vuejs.org/v2/api/#watch
And I agree.

But it is not here -> https://v3.vuejs.org/guide/computed.html#watchers

And that is why so many people fall on this.

![image](https://user-images.githubusercontent.com/37179353/108944654-76132600-765b-11eb-9abe-4ef8d9c65ff4.png)

**Comment by skirtles-code** [comment]
The dotted notation for the `watch` option was due to be removed in Vue 3, so it was removed from the docs. However, to avoid backwards compatibility problems, it was reintroduced just before 3.0.0 was released and hasn't yet been restored to the docs.

I don't think the docs need to make an explicit mention of the need to use quotes around the dotted value. That's a core JavaScript thing, not a Vue requirement. Any examples will be quoted and I think that should be sufficient.

More generally, there is a question here about how watchers should be documented. The guide only mentions the simplest case. The documentation for the various options is in the API Reference and is spread across the various ways of creating a watcher. It isn't as easy as it should be to find the relevant information.

**Comment by NataliaTepluhina** [comment]
First of all, we have it mentioned here with function syntax: https://v3.vuejs.org/api/instance-methods.html#watch

But I agree with API examples for `$watch` and `watch` at least should be consistent. I'll create a PR for this
