### ISSUE TITLE
Page content on v3.vuejs.org/guide jumps 3 times while loading

### ISSUE THREAD

**Issue by opennota** [vuejs/docs-next#996]
If you open https://v3.vuejs.org/guide/events.html in a browser, the content will jump 3 times and end up displaying the code sample starting with `Vue.createApp({` at the top of the page.

Video: https://vimeo.com/537586896

*EDIT: fixed the link

**Comment by skirtles-code** [comment]
I did some preliminary investigation.

The problem is not limited to that page, I could reproduce a similar effect on other pages too.

The jumping seems to be caused by CodePens with editing enabled and the HTML tab visible. The editor grabs focus and if it isn't currently visible the page will scroll down to show it.

The CodePens are loaded into an `iframe` with `loading="lazy"`. This means that many of them don't load when the page first loads, so there isn't necessarily an initial jump. However, slowly scrolling down the page will eventually trigger the `iframe` and then a jump occurs.
